_target_: diffcsp.pl_modules.cspnet.CSPNet
hidden_dim: 256
latent_dim: 0
num_layers: 4
act_fn: silu
dis_emb: sin
num_freqs: 128
edge_style: fc
max_neighbors: ${model.max_neighbors}
cutoff: ${model.radius}
ln: true
ip: true